services:
    tourguide:
        image: tourguideservice:1.0.0
        ports:
        - "8080:8080"
        depends_on:
        - gpsUtil
        - rewardsCentral
        - tripPricer
      
    gpsUtil: 
        image: gpsservice:1.0.0
        ports:
        - "8090:8090"

    rewardsCentral:
        image: rewardservice:1.0.0
        ports:
        - "9000:9000"

    tripPricer:
        image: pricerservice:1.0.0 
        ports:
        - "9010:9010"
