services:
    tourguide:
        image: tourguideservice:1.0.0
        ports:
        - "8080:8080"
        depends_on:
        - gpsUtil
        - rewardsCentral
        - tripPricer
      
    gpsUtil: 
        image: gpsservice:1.0.0
        ports:
        - "5000:5000"

    rewardsCentral:
        image: rewardservice:1.0.0
        ports:
        - "6000:6000"

    tripPricer:
        image: pricerservice:1.0.0 
        ports:
        - "7000:7000"
